jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2

    - name: Install remotes
      run: |
        install.packages('remotes')
      shell: Rscript {0}

    - name: Install dependencies
      run: |
        remotes::install_deps(dependencies = TRUE)
      shell: Rscript {0}

    - name: Test coverage
      run: covr::codecov()
      shell: Rscript {0}
