name: test coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2

    - name: Install dependencies
      run: |
        install.packages('covr')
        remotes::install_deps(dependencies = TRUE)
      shell: Rscript {0}

    - name: Test coverage
      run: covr::codecov()
      shell: Rscript {0}
